Updated ci.yml to baldurk/renderdoc version, agents versioning updated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,8 @@ jobs:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 100
-    - name: Check commit messages
+    - name: Check commit messages (PR)
+      if: ${{ github.event_name == 'pull_request' }}
       run: |
         if git log --oneline | tail -n +2 | head -n 100 | cut -d ' ' -f2- | grep -q '.\{73\}'; then
           (echo -n "::error::";
@@ -33,13 +34,24 @@ jobs:
            git log --oneline | tail -n +2 | head -n 100 | cut -d ' ' -f2- | grep '.\{73\}';) | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
           exit 1;
         fi
+    - name: Check commit messages (Push)
+      if: ${{ github.event_name == 'push' }}
+      run: |
+        if git log --oneline | head -n 100 | cut -d ' ' -f2- | grep -q '.\{73\}'; then
+          (echo -n "::error::";
+           echo "Some commit message summary lines are too long. See CONTRIBUTING.md for more information.";
+           echo "Invalid commits:";
+           echo;
+           git log --oneline | head -n 100 | cut -d ' ' -f2- | grep '.\{73\}';) | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
+          exit 1;
+        fi
   clang-format:
     name: Code formatting check
     runs-on: ubuntu-20.04
     strategy:
       fail-fast: true
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Run clang-format
@@ -64,7 +76,7 @@ jobs:
     strategy:
       fail-fast: true
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Download minimum supported cmake version
@@ -122,7 +134,7 @@ jobs:
             platform: x64
             configuration: Development
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Download optional 3rdparty extras
@@ -155,7 +167,7 @@ jobs:
     env:
       QT_SELECT: qt5
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Install compilation dependencies
@@ -204,7 +216,7 @@ jobs:
             cxx: clang++-12
             type: Debug
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Add LLVM apt repository
@@ -253,9 +265,13 @@ jobs:
     needs: [commit-msg, clang-format]
     runs-on: ubuntu-20.04
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
+    - uses: actions/setup-java@v4
+      with:
+        distribution: 'zulu'
+        java-version: '8'
     - name: Install Android SDK 3859397 and NDK r14b
       run: |
         export ARCH=`uname -m`
@@ -270,6 +286,8 @@ jobs:
         pushd $GITHUB_WORKSPACE/tools/bin
         (yes 2>/dev/null | ./sdkmanager --sdk_root=$GITHUB_WORKSPACE "build-tools;26.0.1" "platforms;android-23") || echo
         popd
+
+        sudo rm -rf /usr/local/lib/android
     - name: Build
       run: |
         mkdir build-android-arm32
@@ -280,7 +298,7 @@ jobs:
   macOS:
     name: Mac
     needs: [commit-msg, clang-format]
-    runs-on: macos-12
+    runs-on: macos-13
     strategy:
       fail-fast: false
       matrix:
@@ -291,7 +309,7 @@ jobs:
           - name: Release
             type: Release
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
       with:
         fetch-depth: 5
     - name: Install Homebrew dependencies
@@ -300,20 +318,18 @@ jobs:
         sudo rm /usr/local/bin/idle3.* || true
         sudo rm /usr/local/bin/pydoc3.* || true
         sudo rm /usr/local/bin/python3.* || true
-        sudo rm /usr/local/bin/python3.*-config || true
         sudo rm /usr/local/bin/2to3 || true
         sudo rm /usr/local/bin/idle3 || true
         sudo rm /usr/local/bin/pydoc3 || true
         sudo rm /usr/local/bin/python3 || true
         sudo rm /usr/local/bin/python3-config || true
         brew update || true
-        brew upgrade aom
-        brew unlink python
-        brew link --overwrite --force python
-        brew unlink python@3.11
-        brew link --overwrite --force python@3.11
-        brew install --overwrite lftp automake pcre qt5
-        brew link --overwrite --force qt5
+        brew unlink python || true
+        brew link --overwrite --force python || true
+        brew unlink python@3.12 || true
+        brew link --overwrite --force python@3.12 || true
+        brew install --overwrite lftp automake pcre qt@5
+        brew link --overwrite --force qt@5
     - name: Build
       run: |
         mkdir build
